### ISSUE TITLE
Error when running Osmedeus on docker

### ISSUE THREAD

**Issue by Benasin** [mablanco/docker-osmedeus#14]
I have followed this installation guide [https://github.com/mablanco/docker-osmedeus/blob/master/README.md]
The console ouput:
`
[*] Loading config file from: /root/.osmedeus/client.conf
----------------------------------------------------------------------
[RUN] Starting Django API
----------------------------------------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2021 - 10:48:11
Django version 2.2.13, using settings 'rest.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /auth/api/token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework_simplejwt/views.py", line 27, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/serializers.py", line 235, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/serializers.py", line 433, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework_simplejwt/serializers.py", line 75, in validate
    data['refresh'] = str(refresh)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework_simplejwt/tokens.py", line 82, in __str__
    return token_backend.encode(self.payload)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework_simplejwt/backends.py", line 35, in encode
    return token.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
[24/Jan/2021 10:48:12] "POST /auth/api/token/ HTTP/1.1" 500 14444
[-] Authentication failed at: http://127.0.0.1:8000/auth/api/token/

        [!] This might happened by running Osmedeus with sudo but the install process running with normal user
        You should install the whole Osmedeus and running it with root user.
        Or whitelist masscan + nmap in sudoers file because it's required sudo permission.

[-] Can't login to get JWT
`

**Comment by mablanco** [comment]
Please post the exact command you used to launch the container. Anyway, it looks like an authentication failure. The README explains that the password to access the Web UI can be obtained executing this command:

`$ docker exec -it osmedeus grep password /root/.osmedeus/client.conf`

**Comment by Benasin** [comment]
I ran these exact commands
```
docker run -it --rm mablanco/osmedeus
docker run -it --rm --name osmedeus -p 8000:8000 mablanco/osmedeus ./osmedeus.py -t website.com
```
I didn't send any login form on the Web UI. It shows these error whenever I start the server.

**Comment by mablanco** [comment]
Please try again with this tag and let me know: `mablanco/osmedeus:2.2-20201202`

**Comment by mablanco** [comment]
I've tracked this issue to the version of PyJWT installed by pip, which is 2.0.1, while in the previous image the version was 1.7.1.

I'm going to report upstream and close this issue as it's beyond the scope of this Docker image. Meanwhile I've deleted the image in Docker Hub and retagged `latest` to point to the latest working image.

Thanks for your report.

**Comment by mablanco** [comment]
Just wanted to let you know that I've implemented a quick fix in the Dockerfile and now the image works properly. You can use again the `latest` image at Docker Hub.

**Comment by Benasin** [comment]
Thank you for the quick fix. Everything is working now.

**Comment by mablanco** [comment]
You're welcome!
