### ISSUE TITLE
TakeOverScanning module Crashed

### ISSUE THREAD

**Issue by wilsonfisk77** [mablanco/docker-osmedeus#5]
i just ran it on Docker first time, and got this error.

```
.................
[*] Waiting for TakeOverScanning module
--~~~=[  TakeOverScanning Done ]=~~~--
--~~~=[  ScreenShot the target ]=~~~--
[+] Make new directory: /home/Osmedeus/workspaces/www.site.com/screenshot
Traceback (most recent call last):
  File "./osmedeus.py", line 151, in <module>
    main()
  File "./osmedeus.py", line 147, in main
    parsing_argument(args)
  File "./osmedeus.py", line 53, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 84, in single_target
    routine.normal(options)
  File "/home/Osmedeus/core/routine.py", line 43, in normal
    screenshot.ScreenShot(options)
  File "/home/Osmedeus/modules/screenshot.py", line 25, in __init__
    self.initial()
  File "/home/Osmedeus/modules/screenshot.py", line 46, in initial
    self.screenshots(self.is_direct)
  File "/home/Osmedeus/modules/screenshot.py", line 69, in screenshots
    if not utils.not_empty_file(input_file):
  File "/home/Osmedeus/core/utils.py", line 158, in not_empty_file
    fpath = os.path.normpath(filepath)
  File "/usr/lib/python3.5/posixpath.py", line 333, in normpath
    initial_slashes = path.startswith(sep)
AttributeError: 'bool' object has no attribute 'startswith'
```

**Comment by mablanco** [comment]
Hi, this is something that seems to be related to the creation of the directories inside the workspace. How did you invoke the container? Did you create a dedicated volume for the workspaces? Are you running the container on Linux?
